#!/usr/bin/env python
# Diffs the library size between scram release and work areas.


from glob import glob
from os import getenv
from os.path import join, getsize, basename
from commands import getstatusoutput
from sys import argv

if __name__ == "__main__":
  if len (argv) == 1:
    path = "."
  elif len(argv) > 2:
    print "Too many options"
  else:
    path = argv[1]

  error, output = getstatusoutput("cd %s; eval `scram run -sh`; echo $CMSSW_RELEASE_BASE; echo $LOCALRT" % path)
  scramArch = getenv("SCRAM_ARCH")
  if error:
    print "Error while retrieving CMSSW release area:"
    print output
  release, work = output.split("\n") 
  workLibs = glob(join(work, "lib", scramArch, "*.so"))
  origLibDir = join(release, "lib", scramArch)

  origLibs = [ join(origLibDir, basename(l)) for l in workLibs ]
  sizes = {}
  for l in workLibs:
    sizes[basename(l)] = int(getsize(l))
  for l in origLibs:
    sizes[basename(l)] -= int(getsize(l))

  total = 0
  for k, v in sizes.iteritems():
    if not v:
      continue
    total += int(v)
    print "%s: %s" % (k, v)
  print "Total (negative means work area is better):", total
